name: ecommerce_app
description: A modern Flutter e-commerce app scaffold (advanced)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^4.0.3
  cached_network_image: ^3.2.3
  flutter_staggered_animations: ^1.1.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.6.0
  shared_preferences: ^2.1.0
  carousel_slider: ^4.2.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
