import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart' as fo; // generated by flutterfire

class FirebaseService {
  static Future<void> init() async {
    await Firebase.initializeApp(
      options: fo.DefaultFirebaseOptions.currentPlatform,
    );
  }
}
